# File format info: https://moz-l10n-config.readthedocs.io/en/latest/fileformat.html
basepath = "."

locales = [
	"en-x-owo",
	"es-419",
	"et",
	"fr",
	"it",
	"ja",
	"ko",
	"pl",
	"pt-BR",
	"vi",
	"zh-Hans"
]

[[paths]]
    reference = "gui/public/i18n/en/*.ftl"
    l10n = "gui/public/i18n/{locale}/*.ftl"
