---
window:
  zoom: 1.5
  width: 800
  height: 800
  posx: -1
  posy: -1
filters:
  type: "prediction"
  amount: 0.2
oscRouter:
  enabled: false
  portIn: 9002
  portOut: 9000
  address: "127.0.0.1"
  trackers: {}
vrcOSC:
  enabled: false
  portIn: 9001
  portOut: 9000
  address: "127.0.0.1"
  trackers:
    right_foot: true
    left_foot: true
    waist: true
keybindings:
  resetBinding: "CTRL+ALT+SHIFT+Y"
  quickResetBinding: "CTRL+ALT+SHIFT+U"
  resetMountingBinding: "CTRL+ALT+SHIFT+I"
  resetDelay: 0
  quickResetDelay: 0
  resetMountingDelay: 0
skeleton:
  toggles: {}
  values: {}
  offsets: {}
legTweaks:
  correctionStrength: 0.3
tapDetection:
  delay: 0.2
  enabled: true
trackers:
  human://CHEST:
    customName: null
    designation: "body:chest"
    hide: false
    adjustment: null
    mountingRotation: null
  human://RIGHT_FOOT:
    customName: null
    designation: "body:right_foot"
    hide: false
    adjustment: null
    mountingRotation: null
  human://RIGHT_HAND:
    customName: null
    designation: "body:right_hand"
    hide: false
    adjustment: null
    mountingRotation: null
  human://HEAD:
    customName: null
    designation: null
    hide: false
    adjustment: null
    mountingRotation: null
  human://LEFT_FOOT:
    customName: null
    designation: "body:left_foot"
    hide: false
    adjustment: null
    mountingRotation: null
  human://RIGHT_ELBOW:
    customName: null
    designation: "body:right_lower_arm"
    hide: false
    adjustment: null
    mountingRotation: null
  human://LEFT_HAND:
    customName: null
    designation: "body:left_hand"
    hide: false
    adjustment: null
    mountingRotation: null
  human://LEFT_KNEE:
    customName: null
    designation: "body:left_upper_leg"
    hide: false
    adjustment: null
    mountingRotation: null
  human://LEFT_ELBOW:
    customName: null
    designation: "body:left_lower_arm"
    hide: false
    adjustment: null
    mountingRotation: null
  human://RIGHT_KNEE:
    customName: null
    designation: "body:right_upper_leg"
    hide: false
    adjustment: null
    mountingRotation: null
  HMD:
    customName: null
    designation: "HMD"
    hide: false
    adjustment: null
    mountingRotation: null
  human://WAIST:
    customName: null
    designation: "body:hip"
    hide: false
    adjustment: null
    mountingRotation: null
bridges:
  steamvr:
    trackers:
      head: false
      right_knee: false
      right_foot: true
      chest: false
      right_hand: false
      left_foot: true
      left_hand: false
      waist: true
      right_elbow: false
      left_knee: false
      left_elbow: false
overlay:
  mirrored: false
  visible: false
autoBone:
  cursorIncrement: 2
  minDataDistance: 1
  maxDataDistance: 1
  numEpochs: 100
  printEveryNumEpochs: 25
  initialAdjustRate: 10.0
  adjustRateMultiplier: 0.995
  slideErrorFactor: 0.0
  offsetSlideErrorFactor: 2.0
  footHeightOffsetErrorFactor: 0.0
  bodyProportionErrorFactor: 0.825
  heightErrorFactor: 0.0
  positionErrorFactor: 0.0
  positionOffsetErrorFactor: 0.0
  calcInitError: false
  targetHeight: -1.0
  randomizeFrameOrder: true
  scaleEachStep: true
  sampleCount: 1000
  sampleRateMs: 20
  saveRecordings: false
modelVersion: "2"
