---
window:
  zoom: 1.5
  width: 1920
  height: 1038
  posx: -7
  posy: 0
filters:
  type: "smoothing"
  amount: 0.39999998
vrcOSC:
  enabled: true
  portIn: 9001
  portOut: 9000
  address: "10.0.0.195"
  trackers:
    head: false
    right_knee: true
    right_foot: true
    chest: true
    right_hand: false
    left_foot: true
    left_hand: false
    waist: true
    right_elbow: false
    left_knee: true
    left_elbow: false
keybindings:
  resetBinding: "CTRL+ALT+SHIFT+Y"
  quickResetBinding: "CTRL+ALT+SHIFT+U"
  resetMountingBinding: "CTRL+ALT+SHIFT+I"
  resetDelay: 0
  quickResetDelay: 0
  resetMountingDelay: 0
skeleton:
  toggles:
    forceArmsFromHMD: false
    extendedKnee: true
    Skating correction: false
    extendedSpine: true
    skatingCorrection: false
    Floor clip: false
    extendedPelvis: true
    floorClip: false
  values:
    hipFromWaistLegsAveraging: 0.4
    hipLegsAveraging: 0.25
    waistFromChestHipAveraging: 0.45
    kneeTrackerAnkleAveraging: 0.75
    waistFromChestLegsAveraging: 0.2
    hipFromChestLegsAveraging: 0.45
  offsets:
    footOffset: 0.05
    footLength: 0.040000007
    waistDistance: 0.044556588
    headShift: 0.08043759
    lowerArmLength: 0.25
    shouldersWidth: 0.39999998
    kneeHeight: 0.45529532
    chestDistance: 0.337984
    neckLength: 0.11089604
    upperArmLength: 0.25
    hipsWidth: 0.26
    torsoLength: 0.4704988
    controllerDistanceZ: 0.13
    controllerDistanceY: 0.035
    elbowOffset: 0.0
    footShift: 0.029999992
    hipOffset: 0.0
    forearmLength: 0.24
    shouldersDistance: 0.09
    legsLength: 0.9114576
    skeletonOffset: 0.0
trackers:
  udp://30:83:98:B6:13:84/0/adj:
    customName: null
    designation: "body:left_foot"
    hide: false
    adjustment: null
    mountingRotation:
      x: 0.0
      "y": 1.0
      z: -0.0
      w: -4.371139E-8
  ? ""
  : customName: null
    designation: null
    hide: false
    adjustment: null
    mountingRotation: null
  udp://40:91:51:45:79:2E/1:
    customName: null
    designation: null
    hide: false
    adjustment: null
    mountingRotation: null
  udp://40:91:51:45:79:2E/0:
    customName: null
    designation: "body:right_lower_leg"
    hide: false
    adjustment: null
    mountingRotation:
      x: 0.0
      "y": 1.0
      z: -0.0
      w: -4.371139E-8
  udp://40:91:51:45:79:2E/1/adj:
    customName: null
    designation: "body:right_lower_leg"
    hide: false
    adjustment: null
    mountingRotation:
      x: 0.0
      "y": 0.0
      z: 0.0
      w: 1.0
  udp://30:83:98:B6:13:84/0:
    customName: null
    designation: "body:left_foot"
    hide: false
    adjustment: null
    mountingRotation:
      x: 0.0
      "y": 1.0
      z: -0.0
      w: -4.371139E-8
  udp://30:83:98:B6:13:84/1:
    customName: null
    designation: null
    hide: false
    adjustment: null
    mountingRotation: null
  udp://30:83:98:B5:F7:BF/0:
    customName: null
    designation: "body:right_foot"
    hide: false
    adjustment: null
    mountingRotation:
      x: 0.0
      "y": 0.0
      z: 0.0
      w: 1.0
  udp://40:91:51:51:71:71/0/adj:
    customName: null
    designation: "body:hip"
    hide: false
    adjustment: null
    mountingRotation:
      x: 0.0
      "y": 0.0
      z: 0.0
      w: 1.0
  udp://40:91:51:51:99:C7/0:
    customName: null
    designation: "body:left_upper_leg"
    hide: false
    adjustment: null
    mountingRotation:
      x: 0.0
      "y": 1.0
      z: -0.0
      w: -4.371139E-8
  udp://40:91:51:51:71:71/0:
    customName: null
    designation: "body:hip"
    hide: false
    adjustment: null
    mountingRotation:
      x: 0.0
      "y": 1.0
      z: 0.0
      w: 6.123234E-17
  human://HEAD:
    customName: null
    designation: null
    hide: false
    adjustment: null
    mountingRotation: null
  udp://40:91:51:51:9B:D4/0:
    customName: null
    designation: "body:right_upper_leg"
    hide: false
    adjustment: null
    mountingRotation:
      x: 0.0
      "y": 1.0
      z: -0.0
      w: -4.371139E-8
  "1PASH5D1P17365_Controller_Right":
    customName: null
    designation: null
    hide: false
    adjustment: null
    mountingRotation: null
  udp://40:91:51:51:9B:D4/1:
    customName: null
    designation: null
    hide: false
    adjustment: null
    mountingRotation: null
  human://LEFT_KNEE:
    customName: null
    designation: null
    hide: false
    adjustment: null
    mountingRotation: null
  human://LEFT_ELBOW:
    customName: null
    designation: null
    hide: false
    adjustment: null
    mountingRotation: null
  udp://30:83:98:B5:D0:39/0/adj:
    customName: null
    designation: "body:chest"
    hide: false
    adjustment: null
    mountingRotation:
      x: 0.0
      "y": 1.0
      z: -0.0
      w: -4.371139E-8
  LIV Virtual Camera (Tracker):
    customName: null
    designation: null
    hide: false
    adjustment: null
    mountingRotation: null
  human://RIGHT_KNEE:
    customName: null
    designation: null
    hide: false
    adjustment: null
    mountingRotation: null
  HMD:
    customName: null
    designation: "HMD"
    hide: false
    adjustment: null
    mountingRotation: null
  udp://30:83:98:B5:D0:39/1:
    customName: "Idiot"
    designation: null
    hide: false
    adjustment: null
    mountingRotation:
      x: 0.0
      "y": 1.0
      z: -0.0
      w: -4.371139E-8
  human://WAIST:
    customName: null
    designation: null
    hide: false
    adjustment: null
    mountingRotation: null
  udp://30:83:98:B5:D0:39/0:
    customName: null
    designation: "body:chest"
    hide: false
    adjustment: null
    mountingRotation:
      x: 0.0
      "y": 1.0
      z: -0.0
      w: -4.371139E-8
  human://CHEST:
    customName: null
    designation: null
    hide: false
    adjustment: null
    mountingRotation: null
  udp://30:83:98:B6:0E:7B/0/adj:
    customName: null
    designation: "body:right_upper_leg"
    hide: false
    adjustment: null
    mountingRotation:
      x: 0.0
      "y": 0.0
      z: 0.0
      w: 1.0
  udp://40:91:51:45:93:E4/0/adj:
    customName: null
    designation: "body:waist"
    hide: false
    adjustment: null
    mountingRotation:
      x: 0.0
      "y": -0.70710677
      z: 0.0
      w: 0.70710677
  udp://40:91:51:44:D9:78/0/adj:
    customName: null
    designation: "body:right_lower_leg"
    hide: false
    adjustment: null
    mountingRotation:
      x: 0.0
      "y": 1.0
      z: -0.0
      w: -4.371139E-8
  human://LEFT_FOOT:
    customName: null
    designation: null
    hide: false
    adjustment: null
    mountingRotation: null
  human://LEFT_HAND:
    customName: null
    designation: "body:left_hand"
    hide: false
    adjustment: null
    mountingRotation: null
  udp://40:91:51:44:D9:78/0:
    customName: null
    designation: "body:left_lower_leg"
    hide: false
    adjustment: null
    mountingRotation:
      x: 0.0
      "y": 1.0
      z: -0.0
      w: -4.371139E-8
  udp://30:83:98:B5:D7:CC/0:
    customName: null
    designation: "body:hip"
    hide: false
    adjustment: null
    mountingRotation:
      x: 0.0
      "y": 0.70710677
      z: 0.0
      w: 0.70710677
  "1PASH5D1P17365":
    customName: null
    designation: null
    hide: false
    adjustment: null
    mountingRotation: null
  udp://40:91:51:51:9B:D4/0/adj:
    customName: null
    designation: "body:left_lower_leg"
    hide: false
    adjustment: null
    mountingRotation:
      x: 0.0
      "y": 1.0
      z: -0.0
      w: -4.371139E-8
  udp://30:83:98:B5:D0:39/1/adj:
    customName: null
    designation: null
    hide: false
    adjustment: null
    mountingRotation: null
  human://RIGHT_FOOT:
    customName: null
    designation: null
    hide: false
    adjustment: null
    mountingRotation: null
  human://RIGHT_HAND:
    customName: null
    designation: "body:right_hand"
    hide: false
    adjustment: null
    mountingRotation: null
  udp://30:83:98:B5:D7:CC/0/adj:
    customName: null
    designation: "body:left_upper_leg"
    hide: false
    adjustment: null
    mountingRotation:
      x: 0.0
      "y": 0.0
      z: 0.0
      w: 1.0
  udp://40:91:51:45:93:E4/1:
    customName: null
    designation: null
    hide: false
    adjustment: null
    mountingRotation: null
  udp://40:91:51:45:93:E4/0:
    customName: null
    designation: "body:right_upper_arm"
    hide: false
    adjustment: null
    mountingRotation:
      x: 0.0
      "y": 0.0
      z: 0.0
      w: 1.0
  udp://30:83:98:B5:F7:BF/0/adj:
    customName: null
    designation: "body:right_foot"
    hide: false
    adjustment: null
    mountingRotation:
      x: 0.0
      "y": 1.0
      z: 0.0
      w: 6.123234E-17
  udp://40:91:51:45:79:2E/0/adj:
    customName: null
    designation: "body:left_upper_leg"
    hide: false
    adjustment: null
    mountingRotation:
      x: 0.0
      "y": 1.0
      z: -0.0
      w: -4.371139E-8
  human://RIGHT_ELBOW:
    customName: null
    designation: null
    hide: false
    adjustment: null
    mountingRotation: null
  udp://30:83:98:B5:E1:E6/0/adj:
    customName: null
    designation: "body:waist"
    hide: false
    adjustment: null
    mountingRotation:
      x: 0.0
      "y": -0.70710677
      z: 0.0
      w: 0.70710677
  udp://30:83:98:B6:0E:7B/0:
    customName: null
    designation: "body:hip"
    hide: false
    adjustment: null
    mountingRotation:
      x: 0.0
      "y": 1.0
      z: -0.0
      w: -4.371139E-8
  "1PASH5D1P17365_Controller_Left":
    customName: null
    designation: null
    hide: false
    adjustment: null
    mountingRotation: null
bridges:
  steamvr:
    trackers:
      right_knee: true
      head: false
      right_foot: true
      chest: true
      right_hand: false
      left_foot: true
      left_hand: false
      waist: true
      right_elbow: false
      left_knee: true
      left_elbow: false
  steamvr_feeder:
    trackers: {}
overlay:
  mirrored: false
  visible: true
autoBone:
  cursorIncrement: 2
  minDataDistance: 1
  maxDataDistance: 1
  numEpochs: 100
  printEveryNumEpochs: 25
  initialAdjustRate: 10.0
  adjustRateMultiplier: 0.995
  slideErrorFactor: 0.0
  offsetSlideErrorFactor: 2.0
  footHeightOffsetErrorFactor: 0.0
  bodyProportionErrorFactor: 0.825
  heightErrorFactor: 0.0
  positionErrorFactor: 0.0
  positionOffsetErrorFactor: 0.0
  calcInitError: false
  targetHeight: -1.0
  randomizeFrameOrder: true
  scaleEachStep: true
  sampleCount: 1000
  sampleRateMs: 20
  saveRecordings: false
modelVersion: "2"
